services:
  nats-1:
    image: nats:latest
    container_name: nats-1
    ports:
      - "4222:4222"
      - "8222:8222"
      - "6222:6222"
    volumes:
      - ./server.conf:/etc/nats-server/server.conf:ro
    command: -c /etc/nats-server/server.conf --server_name nats-1

  nats-2:
    image: nats:latest
    container_name: nats-2
    ports:
      - "4223:4222"
      - "8223:8222"
      - "6223:6222"
    volumes:
      - ./server.conf:/etc/nats-server/server.conf:ro
    command: -c /etc/nats-server/server.conf --server_name nats-2

  nats-3:
    image: nats:latest
    container_name: nats-3
    ports:
      - "4224:4222"
      - "8224:8222"
      - "6224:6222"
    volumes:
      - ./server.conf:/etc/nats-server/server.conf:ro
    command: -c /etc/nats-server/server.conf --server_name nats-3
